module.exports = {
  POLL_STATUS: {
    ACTIVE: 'active',
    CLOSED: 'closed',
    EXPIRED: 'expired'
  },
  USER_TYPES: {
    TEACHER: 'teacher',
    STUDENT: 'student'
  },
  ERROR_CODES: {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    POLL_NOT_FOUND: 'POLL_NOT_FOUND',
    POLL_ALREADY_ANSWERED: 'POLL_ALREADY_ANSWERED',
    POLL_EXPIRED: 'POLL_EXPIRED',
    STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    DUPLICATE_NAME: 'DUPLICATE_NAME',
    NO_ACTIVE_POLL: 'NO_ACTIVE_POLL',
    POLL_CREATION_BLOCKED: 'POLL_CREATION_BLOCKED'
  },
  DEFAULT_POLL_TIME_LIMIT: 60
};